services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zakjakub\OswisTemplateExampleBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Repository,Filter,Tests,Kernel.php}'
        public: true

    Zakjakub\OswisTemplateExampleBundle\Service\:
        resource: '../../Service/*'
        public: true

    Zakjakub\OswisTemplateExampleBundle\Api\Dto\:
        resource: '../../Api/Dto/*'
        public: true

    Zakjakub\OswisTemplateExampleBundle\Api\EventSubscriber\:
        resource: '../../Api/EventSubscriber/*'
        public: true
